# Generated by Django 4.1.1 on 2022-09-11 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_contactforminquiry_contactformmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmessage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
