# Generated by Django 4.1.1 on 2022-09-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactformmessage_responded_alter_post_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformmessage',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='responded',
            field=models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
