# Generated by Django 4.1.1 on 2022-09-30 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_category_alter_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='fave', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='new_author',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.userprofile'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.post')),
                ('user', models.ManyToManyField(blank=True, to='main.userprofile')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
