# Generated by Django 4.1.1 on 2022-09-30 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_favourite_post_new_author_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
