# Generated by Django 4.1.1 on 2022-09-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='new_author',
            new_name='author',
        ),
    ]
