# Generated by Django 4.1.1 on 2022-10-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_new_author_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='main.userprofile'),
        ),
    ]
